spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/db1"
    username: "root"
    password: "testPassword"
  application:
    eth:
      alchemyAPIKey: "L_LOumhDPdpGwnXsfG7X-e0_GOs2WyU1"
      alchemyBaseUrl: "https://eth-mainnet.alchemyapi.io/v2/"
      contractAddress: "0xbc4ca0eda7647a8ab7c2061c2e118a18a936f13d"
      eventHashSignature: "0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef"
      numberOfBlocksAgo: 270 # 270 => Roughly an hours worth of blocks to look back
    scheduler-config:
      schedulerFixedDelayStringMs: 60000
